stages:
  - test
  - deploy

image: docker

services:
  - docker:dind

variables:
  IMAGE: "lukehowelldev/rancher-cli"
  TAG: "latest"
  VERSION: "v0.4.1"

before_script:
  - apk update
  - apk add m4 make

test with entrypoint:
  stage: test
  variables:
    ENTRYPOINT: "rancher"
  script:
    - make
    - make test/with-entrypoint

test without entrypoint:
  stage: test
  script:
    - make
    - make test/without-entrypoint

deploy with entrypoint:
  stage: deploy
  variables:
    ENTRYPOINT: "rancher"
  script:
    - make
    - make test/with-entrypoint
    - make deploy
  only:
    - master

deploy without entrypoint:
  stage: deploy
  variables:
    TAG: "no-entrypoint"
  script:
    - make
    - make test/without-entrypoint
    - make deploy
  only:
    - master
